'use strict';
const fs = require('fs');
const crypto = require('crypto');
const { FILES, TOTAL_TARGET, PER_TOPIC_TARGET, PROD_REF, ensureDirs } = require('./config');
const { readJson, writeJson, writeCheckpoint } = require('./state');
const { validateFinalSet } = require('./editorial-rules');
const { validateSpanishOrthography } = require('./orthography');
const { buildPayload } = require('./upload-staging');

function generateBatchCode(candidates) {
  const now = new Date();
  const ts = now.toISOString().replace(/[-:.TZ]/g, '').slice(0, 14);
  const fingerprints = candidates.map((c) => c.duplicate_fingerprint).sort().join('|');
  const hash = crypto.createHash('sha256').update(fingerprints).digest('hex').slice(0, 8);
  return `qgen_${ts}_${hash}`;
}

function buildSQL(batchCode, candidatePayload) {
  const candidatesJson = JSON.stringify(candidatePayload, null, 0);

  return `-- Generated by qgen:prepare-upload (v5)
-- batch_code: ${batchCode}
-- total_candidates: ${candidatePayload.length}
-- project_ref: ${PROD_REF}
-- target: generated_topic_batches, generated_topic_candidates
-- forbidden: temas, votos, tema_sugerencias, profiles, auth.users
-- will_publish: false
-- will_convert: false

BEGIN;

DO $qgen$
DECLARE
  v_batch_id uuid;
  v_expected_count integer := ${TOTAL_TARGET};
  v_inserted_count integer;
BEGIN

  INSERT INTO public.generated_topic_batches(
    batch_code, source, ideological_profile, status, expected_count, notes
  )
  VALUES (
    '${batchCode}',
    'qgen_v5',
    'liberal_democratic',
    'draft',
    v_expected_count,
    'Carga controlada generada por qgen v5. No publica ni convierte. Revision humana obligatoria.'
  )
  RETURNING id INTO v_batch_id;

  INSERT INTO public.generated_topic_candidates(
    batch_id, titulo, descripcion, tipo_votacion, opciones,
    publico_objetivo, taxonomy_draft, ideological_axis, deliberative_tension,
    neutrality_notes, quality_notes, risk_flags,
    requires_source, source_required_reason,
    human_review_required, quality_score, neutrality_score,
    duplicate_fingerprint, raw_payload
  )
  SELECT
    v_batch_id,
    btrim(c->>'titulo'),
    nullif(btrim(coalesce(c->>'descripcion', '')), ''),
    btrim(c->>'tipo_votacion'),
    coalesce(c->'opciones', '[]'::jsonb),
    btrim(c->>'publico_objetivo'),
    coalesce(c->'taxonomy_draft', '{}'::jsonb),
    nullif(btrim(coalesce(c->>'ideological_axis', '')), ''),
    nullif(btrim(coalesce(c->>'deliberative_tension', '')), ''),
    nullif(btrim(coalesce(c->>'neutrality_notes', '')), ''),
    nullif(btrim(coalesce(c->>'quality_notes', '')), ''),
    coalesce(c->'risk_flags', '[]'::jsonb),
    coalesce(nullif(c->>'requires_source', '')::boolean, false),
    nullif(btrim(coalesce(c->>'source_required_reason', '')), ''),
    true,
    null::integer,
    null::integer,
    btrim(c->>'duplicate_fingerprint'),
    c
  FROM jsonb_array_elements($candidates_data$${candidatesJson}$candidates_data$::jsonb) AS c;

  SELECT count(*)::integer INTO v_inserted_count
  FROM public.generated_topic_candidates
  WHERE batch_id = v_batch_id;

  IF v_inserted_count <> v_expected_count THEN
    RAISE EXCEPTION 'qgen_count_mismatch: expected % got %', v_expected_count, v_inserted_count;
  END IF;

  UPDATE public.generated_topic_batches
  SET status = 'loaded', inserted_count = v_inserted_count
  WHERE id = v_batch_id;

  RAISE NOTICE 'qgen_ok: batch_id=%, inserted=%', v_batch_id, v_inserted_count;

END $qgen$;

COMMIT;
`;
}

function prepareUpload() {
  ensureDirs();

  const dryRun = readJson(FILES.upload, null);
  if (!dryRun || dryRun.status !== 'ok' || dryRun.would_insert !== TOTAL_TARGET) {
    throw new Error('dry_run_ok_required_before_prepare_upload');
  }

  const existingApplyResult = readJson(FILES.applyResult, null);
  if (existingApplyResult && existingApplyResult.status === 'ok') {
    throw new Error('apply_upload_already_completed: run qgen:new-batch for a new lote');
  }

  const candidates = readJson(FILES.final, []);
  if (!Array.isArray(candidates) || candidates.length !== TOTAL_TARGET) {
    throw new Error(`prepare_upload_invalid_candidate_count: ${candidates.length}`);
  }

  const validation = validateFinalSet(candidates);
  if (!validation.ok) {
    throw new Error(`prepare_upload_final_invalid: ${validation.errors.join(',')}`);
  }

  const orthographyErrors = candidates.flatMap((c) => {
    const result = validateSpanishOrthography(c);
    return result.ok ? [] : result.errors.map((e) => `${c.candidate_id}:${e}`);
  });
  if (orthographyErrors.length > 0) {
    throw new Error(`prepare_upload_orthography_invalid: ${orthographyErrors.slice(0, 3).join(',')}`);
  }

  const topicCounts = {};
  for (const c of candidates) {
    const topic = c.raw_payload?.topic_target || c.ideological_axis || 'unknown';
    topicCounts[topic] = (topicCounts[topic] || 0) + 1;
  }
  for (const [topic, count] of Object.entries(topicCounts)) {
    if (count !== PER_TOPIC_TARGET) {
      throw new Error(`prepare_upload_invalid_topic_count: ${topic}=${count}`);
    }
  }

  const batchCode = generateBatchCode(candidates);
  const payload = buildPayload(candidates);

  const stagingPayload = {
    batch_code: batchCode,
    project_ref: PROD_REF,
    source: 'qgen_v5',
    ideological_profile: 'liberal_democratic',
    expected_count: TOTAL_TARGET,
    status: 'prepared',
    topics: Object.keys(topicCounts).length,
    per_topic: PER_TOPIC_TARGET,
    candidates: payload,
    prepared_at: new Date().toISOString(),
    generator_version: 'v5',
    forbidden_tables: ['temas', 'votos', 'tema_sugerencias'],
    will_publish: false,
    will_convert: false,
  };

  writeJson(FILES.stagingPayload, stagingPayload);
  fs.writeFileSync(FILES.stagingSQL, buildSQL(batchCode, payload), 'utf8');

  writeCheckpoint('PREPARE_UPLOAD', 'checkpoint', {
    processed_count: TOTAL_TARGET,
    accumulated_count: TOTAL_TARGET,
    topic_progress: { topics: Object.keys(topicCounts).length, per_topic: PER_TOPIC_TARGET },
    batch_code: batchCode,
    next_action: 'qgen:apply-upload',
    timestamp: new Date().toISOString(),
  });

  return { batch_code: batchCode, candidates_count: candidates.length };
}

module.exports = { prepareUpload, generateBatchCode };
